### ISSUE TITLE
RTCPeerConnection negotiationneeded multiple times

### ISSUE THREAD

**Issue by vunb** [roomrtc/mediaserver#5]
```bash
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ INFO ] negotiationneeded sendSdpOffer back: btnkQHkgxTC_DGreAAAD
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ INFO ] negotiationneeded sendSdpOffer back: btnkQHkgxTC_DGreAAAD
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ INFO ] negotiationneeded sendSdpOffer back: btnkQHkgxTC_DGreAAAD
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ INFO ] negotiationneeded sendSdpOffer back: btnkQHkgxTC_DGreAAAD
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ ERROR ] sendSdpToPeer error: InvalidStateError: busy
    at klass (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/errors.js:9:4)
    at RTCPeerConnectionPlanB.createOffer (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:202:26)
    at Peer.sendSdpOffer (/home/vunb/roomrtc/mediaserver-2/peer.js:88:24)
    at RTCPeerConnectionPlanB.pc.on (/home/vunb/roomrtc/mediaserver-2/peer.js:109:18)
    at emitNone (events.js:91:20)
    at RTCPeerConnectionPlanB.emit (events.js:185:7)
    at Timeout._negotiationNeededTimer.setTimeout [as _onTimeout] (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:508:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ ERROR ] sendSdpToPeer error: InvalidStateError: busy
    at klass (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/errors.js:9:4)
    at RTCPeerConnectionPlanB.createOffer (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:202:26)
    at Peer.sendSdpOffer (/home/vunb/roomrtc/mediaserver-2/peer.js:88:24)
    at RTCPeerConnectionPlanB.pc.on (/home/vunb/roomrtc/mediaserver-2/peer.js:109:18)
    at emitNone (events.js:91:20)
    at RTCPeerConnectionPlanB.emit (events.js:185:7)
    at Timeout._negotiationNeededTimer.setTimeout [as _onTimeout] (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:508:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ ERROR ] sendSdpToPeer error: InvalidStateError: busy
    at klass (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/errors.js:9:4)
    at RTCPeerConnectionPlanB.createOffer (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:202:26)
    at Peer.sendSdpOffer (/home/vunb/roomrtc/mediaserver-2/peer.js:88:24)
    at RTCPeerConnectionPlanB.pc.on (/home/vunb/roomrtc/mediaserver-2/peer.js:109:18)
    at emitNone (events.js:91:20)
    at RTCPeerConnectionPlanB.emit (events.js:185:7)
    at Timeout._negotiationNeededTimer.setTimeout [as _onTimeout] (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:508:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
RoomRTC : Peer Agi9JgQTZ7pAnzaSAAAC [ INFO ] pc.setLocalDescription(desc); ....
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ INFO ] pc.setLocalDescription(desc); ....
RoomRTC : Peer Agi9JgQTZ7pAnzaSAAAC [ INFO ] Preparing sendSdpOffer to peer
RoomRTC : Peer btnkQHkgxTC_DGreAAAD [ INFO ] Preparing sendSdpOffer to peer
RoomRTC : Peer Q9X4CRsiFIYB_sJPAAAB [ INFO ] negotiationneeded sendSdpOffer back: Q9X4CRsiFIYB_sJPAAAB
RoomRTC : Peer Q9X4CRsiFIYB_sJPAAAB [ INFO ] negotiationneeded sendSdpOffer back: Q9X4CRsiFIYB_sJPAAAB
RoomRTC : Peer Q9X4CRsiFIYB_sJPAAAB [ ERROR ] sendSdpToPeer error: InvalidStateError: busy
    at klass (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/errors.js:9:4)
    at RTCPeerConnectionPlanB.createOffer (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:202:26)
    at Peer.sendSdpOffer (/home/vunb/roomrtc/mediaserver-2/peer.js:88:24)
    at RTCPeerConnectionPlanB.pc.on (/home/vunb/roomrtc/mediaserver-2/peer.js:109:18)
    at emitNone (events.js:91:20)
    at RTCPeerConnectionPlanB.emit (events.js:185:7)
    at Timeout._negotiationNeededTimer.setTimeout [as _onTimeout] (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:508:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
RoomRTC : Peer Q9X4CRsiFIYB_sJPAAAB [ ERROR ] sendSdpToPeer error: TypeError: Cannot read property 'dtlsLocalParameters' of undefined
    at RTCPeerConnectionPlanB._createLocalDescription (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionPlanB.js:260:43)
    at _setUpOffer.then (/home/vunb/roomrtc/mediaserver-2/node_modules/mediasoup/lib/webrtc/RTCPeerConnection/RTCPeerConnectionCommon.js:225:33)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ibc** [comment]
Hi, you may want to upgrade to mediasoup 1.0.0. The "TypeError: Cannot read property 'dtlsLocalParameters' of undefined" is fixed there.

Regarding the original issue (negotiationneeded multiple times) it should not happen. I've never experimented it so I expect it to be something wrong in the API usage.

**Comment by vunb** [comment]
Thank you @ibc . I will try it soon. Hope version 1.0 has great things to be updated 😄
